ARG BASEIMAGE
FROM ${BASEIMAGE}

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    # curl is required to download the vscode-server
    curl \
    python3 \
    python3-pip \
    python3-venv \
    git \
    xz-utils

RUN apt-get clean && \ 
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

RUN npm update -g npm && \
    npm install -g typescript && \
    npm install -g @vscode/vsce

# BUILD
ADD src/tmp/gemini-cli /opt/gemini-cli
RUN cd /opt/gemini-cli && \
    npm install && \
    cp bundle/gemini.js /usr/local/bin/gemini.js && \
    chmod +x /usr/local/bin/gemini.js && \
    chown ${IMGUSER}:${IMGUSER} /usr/local/bin/gemini.js
# clean up
RUN cd /opt && rm -rf gemini-cli
RUN cd /home/${IMGUSER}/ && \
    echo "alias gemini='/usr/local/bin/gemini.js'" >> .bash_aliases && \
    chmod +x .bash_aliases && \
    chown ${IMGUSER}:${IMGUSER} .bash_aliases

USER ${IMGUSER}
